<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>xyz</string>
		<string>cljs</string>
		<string>clj</string>
		<string>cljc</string>
	</array>
	<key>name</key>
	<string>Lisp</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#all</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>all</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#sexpr</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#special</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#word</string>
				</dict>
			</array>
		</dict>
		<key>sexpr</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>end</key>
					<string>(\))</string>
					<key>name</key>
					<string>sexpr.list</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#all</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\[)</string>
					<key>end</key>
					<string>(\])</string>
					<key>name</key>
					<string>sexpr.vec</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#all</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\#{)</string>
					<key>end</key>
					<string>(\})</string>
					<key>name</key>
					<string>sexpr.set</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#all</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\{)</string>
					<key>end</key>
					<string>(\})</string>
					<key>name</key>
					<string>sexpr.hashmap</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#all</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>shadow_all</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#shadow_sexpr</string>
				</dict>
				<dict>
					<key>name</key>
					<string>shadow_word</string>
				</dict>
			</array>
		</dict>
		<key>shadow_sexpr</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>end</key>
					<string>(\))</string>
					<key>name</key>
					<string>shadow.sexpr.list</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#shadow_all</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\[)</string>
					<key>end</key>
					<string>(\])</string>
					<key>name</key>
					<string>shadow.sexpr.vec</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#shadow_all</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\#{)</string>
					<key>end</key>
					<string>(\})</string>
					<key>name</key>
					<string>shadow.sexpr.set</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#shadow_all</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\{)</string>
					<key>end</key>
					<string>(\})</string>
					<key>name</key>
					<string>shadow.sexpr.hashmap</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#shadow_all</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>special</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>applyEndPatternLast</key>
					<integer>1</integer>
					<key>begin</key>
					<string>(#_\s*)</string>
					<key>end</key>
					<string>([\W])\b</string>
					<key>name</key>
					<string>ignore</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#shadow_all</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>word</key>
		<dict>
			<key>match</key>
			<string>([^\(\)\{\}\[\]\s]+)</string>
			<key>name</key>
			<string>word</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lisp</string>
	<key>uuid</key>
	<string>-5584466320959560-558446636-69771</string>
</dict>
</plist>
